image: node:20

pages:
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration production
    - touch public/.nojekyll
  artifacts:
    paths:
      - public
  only:
    - main
